# Generated by Django 4.0.4 on 2022-06-02 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogx', '0002_remove_video_content_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='subtegory',
            new_name='subcategory',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogx.profile'),
        ),
    ]
