# Generated by Django 4.0.4 on 2022-05-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogx', '0002_likes_subcategory_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'get_latest_by': 'add_date'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'date_added'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['pub_time', 'update_time']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'get_latest_by': ['pub_time', 'update_time']},
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategory',
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
