# Generated by Django 4.0.4 on 2022-06-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogx', '0003_rename_subtegory_video_subcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
